// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from "dotenv";
// Prefer .env.local (e.g. local Docker) over .env when running Prisma CLI
dotenv.config({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";
import { env } from "./src/models/envs/envs.schema";
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed:`tsx prisma/seed.ts`
  },
  datasource: {
    //url: process.env["DATABASE_URL"],
    url:env.DATABASE_URL,

  },
});
