import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Rubik_Wet_Paint } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
import { AppSidebar } from "@/shared/ui/AppSidebar.component";
import { SidebarInset } from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/** Distressed / hand-painted display — success toasts & alert-style copy */
const toastAlertFont = Rubik_Wet_Paint({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-toast-alert",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans dark", inter.variable, toastAlertFont.variable)}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <Providers>
          <AppSidebar />
          <SidebarInset>
          {children}
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
